version: '3.5'

networks:
    backend:
        driver: bridge

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "80:80"
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            TZ: 'Asia/Almaty'
        networks:
            - backend

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=elasticsearch-cluster
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xmx2g -Xms2g
            - "xpack.security.enabled=false"
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - backend

    php-8.2:
        build:
            context: docker/php/8.2
            dockerfile: Dockerfile
            args:
                DOCKER_PHP_VERSION: '8.2'
                TZ: 'Asia/Almaty'
        working_dir: /var/www
        container_name: php-8.2
        volumes:
            - .:/var/www
            - ./docker/php/8.2/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php-workers/8.2/supervisor.d:/etc/supervisor.d
        ports:
            - "9082:9000"
        networks:
            - backend
